### ISSUE TITLE
when i run on RaspberryPI i got Error like:[826:0100/000000:ERROR:nss_util.cc(686)] Failed to load NSS libraries.

### ISSUE THREAD

**Issue by ipconfiger** [toxygen/armhf-node-webkit#2]
(nw:824): Gtk-WARNING **: cannot open display: 
linaro@cubietruck:~/armhf-node-webkit-master$ [826:0100/000000:ERROR:nss_util.cc(686)] Failed to load NSS libraries.
[826:0100/000000:ERROR:zygote_linux.cc(478)] write: 断开的管道

**Comment by toxygen** [comment]
This should be harmless message.
However, if it causes crash (does it?), you can try doing this:

```
sudo ln -s /usr/lib/arm-linux-gnueabihf/nss/ /usr/lib/nss
```

I will be making a new version soon, so it might be fixed by then

**Comment by misterhayman** [comment]
I get the same error messages, but they do appear to be harmless.  Looking forward to the new version!  Thanks for posting this for us to use!

**Comment by toxygen** [comment]
new arm builds are provided in this repo: https://github.com/LeonardLaszlo/nw.js-armv7-binaries
