### ISSUE TITLE
streaming html5 with nw - not working

### ISSUE THREAD

**Issue by rafaelAFN** [toxygen/armhf-node-webkit#3]
Hi toxygen. 

I tried to use the package to run in the BBB. I can open the nw, look attachment, but I can not view the streaming video. 
Can you help me? The site I'm trying to use to display the streaming is www.simplewebrtc.org/demo.html 

Thank you.

PS: Please discard the first error, it happened when I tried to open the debug
![screenshot from 2014-10-17 20_14_49](https://cloud.githubusercontent.com/assets/6683624/4709450/671ed90e-589f-11e4-9433-7c7eff3cb9d8.png)

**Comment by toxygen** [comment]
Sorry for the delay, I'll be building a new version soon, so you can try it then.

**Comment by toxygen** [comment]
Forgotten issue. Anyway, new arm builds are available here: https://github.com/LeonardLaszlo/nw.js-armv7-binaries
