### ISSUE TITLE
Promises support

### ISSUE THREAD

**Issue by fczuardi** [toxygen/armhf-node-webkit#4]
What version of webkit is this using? It looks like it might be an old one that doesn't support Promises, when I try to run a node-webkit based app that uses it this is the error I get:

> Error undefined is not a function 
> [21053:0223/144934:INFO:CONSOLE(101)] "Uncaught ReferenceError: Promise is not defined", source: app://./js/boot.js (101)

**Comment by toxygen** [comment]
Latest build is based on 0.7.1, which is pretty old. I might be making a new build in next week or two

**Comment by fczuardi** [comment]
cool! what do you use to make a build? is it a process that could somehow be automated eventually?

Thanks for making the builds available, it was really helpful :)

**Comment by toxygen** [comment]
I use odroid-x2. Unfortunately, the process can't be automated because I need to make different changes with each new version to make it compile.

**Comment by fczuardi** [comment]
What about cross-compiling? Is it even an option? Being able to open up a cloud machine (digital ocean, amazon ec2, linode, etc) for a couple of hours with a nice config and get the binary generated would be great, and faster and cheap.

**Comment by toxygen** [comment]
Yeah, cross-compiling is an option. But I prefer native compiling in the age of quad-core 2ghz arms :)

**Comment by toxygen** [comment]
I will be looking into compiling nwjs on arm in following weeks. 
As of now, there are some builds available here: https://github.com/LeonardLaszlo/nw.js-armv7-binaries
